/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>

void
unpackDeviceIdIdentity0(
	uint32_t *	registerValue,
	uint32_t *	value
);

void
unpackDeviceIdIdentity1(
	uint32_t *	registerValue,
	uint32_t *	value
);
