# Auto-generated by regmapper - DO NOT MODIFY



class DeviceId:
    BASE_ADDR = 0xfffe000
    class Identity0:
        ADDR = 0xfffe000
        class Value:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_value = (reg_val >> 0) & 0xffffffff
            return f_value


        @staticmethod
        def pack(f_value: int) -> int:
            reg_val = 0
            reg_val |= (f_value & 0xffffffff) << 0
            return reg_val
    class Identity1:
        ADDR = 0xfffe004
        class Value:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_value = (reg_val >> 0) & 0xffffffff
            return f_value


        @staticmethod
        def pack(f_value: int) -> int:
            reg_val = 0
            reg_val |= (f_value & 0xffffffff) << 0
            return reg_val
