/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "device_id_pack_unpack.h"

void
unpackDeviceIdIdentity0(
	uint32_t *	registerValue,
	uint32_t *	value)
{
	uint32_t reg_val = *registerValue;
	*value= (uint32_t)((reg_val >> 0) & 0xffffffff);
}

void
unpackDeviceIdIdentity1(
	uint32_t *	registerValue,
	uint32_t *	value)
{
	uint32_t reg_val = *registerValue;
	*value= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
