/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

void	getDeviceIdIdentity0(
	uint32_t *	value
);

void	getDeviceIdIdentity1(
	uint32_t *	value
);
