/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "device_id_regs.h"

void
getDeviceIdIdentity0(
	uint32_t *	value)
{
	uint32_t reg_val = *(volatile uint32_t *)(0xfffe000);
	*value= (uint32_t)((reg_val >> 0) & 0xffffffff);
}

void
getDeviceIdIdentity1(
	uint32_t *	value)
{
	uint32_t reg_val = *(volatile uint32_t *)(0xfffe004);
	*value= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
